export const LabelMapper: { [id: string]: string } = {
  "All_Causes": "All Causes",
  "I.Communicable,_maternal,_perinatal_and_nutritional_conditions": "I.Communicable, maternal, perinatal and nutritional conditions",
  "A.Infectious_and_parasitic_diseases": "A.Infectious and parasitic diseases",
  "1.Tuberculosis": "1.Tuberculosis",
  "2.STDs_excluding_HIV": "2.STDs excluding HIV",
  "a.Syphilis": "a.Syphilis",
  "b.Chlamydia": "b.Chlamydia",
  "c.Gonorrhoea": "c.Gonorrhoea",
  "d.Trichomoniasis": "d.Trichomoniasis",
  "e.Gential_Herpes": "e.Gential Herpes",
  "f.Other_STDs": "f.Other STDs",
  "3.HIV_AIDS": "3.HIV/AIDS",
  "4.Diarrhoeal_diseases": "4.Diarrhoeal diseases",
  "5.Childhood-cluster_diseases": "5.Childhood-cluster diseases",
  "a.Whooping_cough": "a.Whooping cough",
  "b.Diphtheria": "b.Diphtheria",
  "c.Measles": "c.Measles",
  "d.Tetanus": "d.Tetanus",
  "6.Meningitis": "6.Meningitis",
  "7.Encephalitis": "7.Encephalitis",
  "8.Hepatitis": "8.Hepatitis",
  "a.Acute_hepatitis_A": "a.Acute hepatitis A",
  "b.Acute_hepatitis_B": "b.Acute hepatitis B",
  "c.Acute_hepatitis_C": "c.Acute hepatitis C",
  "d.Acute_hepatitis_E": "d.Acute hepatitis E",
  "9.Parasitic_and_vector_diseases": "9.Parasitic and vector diseases",
  "a.Malaria": "a.Malaria",
  "b.Trypanosomiasis": "b.Trypanosomiasis",
  "c.Chagas_disease": "c.Chagas disease",
  "d.Schistosomiasis": "d.Schistosomiasis",
  "e.Leishmaniasis": "e.Leishmaniasis",
  "f.lymphatic_filariasis": "f.lymphatic filariasis",
  "g.Onchocerciasis": "g.Onchocerciasis",
  "h.Cysticercosis": "h.Cysticercosis",
  "i.Echinococcosis": "i.Echinococcosis",
  "j.Dengue": "j.Dengue",
  "k.Trachoma": "k.Trachoma",
  "l.Yellow_fever": "l.Yellow fever",
  "m.Rabies": "m.Rabies",
  "10.Intestinal_nematode_infections": "10.Intestinal nematode infections",
  "a.Ascariasis": "a.Ascariasis",
  "b.Trichuriasis": "b.Trichuriasis",
  "c.Hookworm_disease": "c.Hookworm disease",
  "d.Food-borne_trematodes": "d.Food-borne trematodes",
  "11.Leprosy": "11.Leprosy",
  "12.Other_infectious_diseases": "12.Other infectious diseases",
  "B.Respiratory_Infectious_": "B.Respiratory Infectious ",
  "1.Lower_respiratory_infections": "1.Lower respiratory infections",
  "2.COVID-19": "2.COVID-19",
  "3.Upper_respiratory_infections": "3.Upper respiratory infections",
  "4.Otitis_media": "4.Otitis media",
  "C.Maternal_conditions": "C.Maternal conditions",
  "D.Neonatal_conditions": "D.Neonatal conditions",
  "1.Preterm_birth_complications": "1.Preterm birth complications",
  "2.Birth_asphyxia_and_birth_trauma": "2.Birth asphyxia and birth trauma",
  "3.Neonatal_sepsis_and_infections": "3.Neonatal sepsis and infections",
  "4.Other_neonatal_conditions": "4.Other neonatal conditions",
  "E.Nutritional_deficiencies": "E.Nutritional deficiencies",
  "1.Protein-energy_malnutrition": "1.Protein-energy malnutrition",
  "2.Iodine_deficiency": "2.Iodine deficiency",
  "3.Vitamin_A_deficiency": "3.Vitamin A deficiency",
  "4.Iron-deficiency_anaemia": "4.Iron-deficiency anaemia",
  "5.Other_nutritional_deficiencies": "5.Other nutritional deficiencies",
  "II.Noncommunicable_diseases": "II.Noncommunicable diseases",
  "A.Malignant_neoplasms": "A.Malignant neoplasms",
  "1.Mouth_and_oropharynx_cancers": "1.Mouth and oropharynx cancers",
  "a.Lip_and_oral_cavity": "a.Lip and oral cavity",
  "b.Nasopharynx": "b.Nasopharynx",
  "c.Other_pharynx": "c.Other pharynx",
  "2.Oesophagus_cancer": "2.Oesophagus cancer",
  "3.Stomach_cancer": "3.Stomach cancer",
  "4.Colon_and_rectum_cancers": "4.Colon and rectum cancers",
  "5.Liver_cancer": "5.Liver cancer",
  "a.Liver_cancer_secondary_to_hepatitis_B": "a.Liver cancer secondary to hepatitis B",
  "b.Liver_cancer_secondary_to_hepatitis_C": "b.Liver cancer secondary to hepatitis C",
  "c.Liver_cancer_secondary_to_alcohol_use": "c.Liver cancer secondary to alcohol use",
  "d.Other_liver_cancer": "d.Other liver cancer",
  "6.Pancreas_cancer": "6.Pancreas cancer",
  "7.Trachea,_bronchus,_lung_cancers": "7.Trachea, bronchus, lung cancers",
  "8.Melanoma_and_other_skin_cancers": "8.Melanoma and other skin cancers",
  "a.Malignant_skin_melanoma": "a.Malignant skin melanoma",
  "b.Non-melanoma_skin_cancer": "b.Non-melanoma skin cancer",
  "9.Breast_cancer": "9.Breast cancer",
  "10.Cervix_uteri_cancer": "10.Cervix uteri cancer",
  "11.Corpus_uteri_cancer": "11.Corpus uteri cancer",
  "12.Ovary_cancer": "12.Ovary cancer",
  "13.Prostate_cancer": "13.Prostate cancer",
  "14.Testicular_cancer": "14.Testicular cancer",
  "15.Kidney_cancer": "15.Kidney cancer",
  "16.Bladder_cancer": "16.Bladder cancer",
  "17.Brain_and_nervous_system_cancers": "17.Brain and nervous system cancers",
  "18.Gallbladder_and_biliary_tract_cancer": "18.Gallbladder and biliary tract cancer",
  "19.Larynx_cancer": "19.Larynx cancer",
  "20.Thyroid_cancer": "20.Thyroid cancer",
  "21.Mesothelioma": "21.Mesothelioma",
  "22.Lymphomas,_multiple_myeloma": "22.Lymphomas, multiple myeloma",
  "a.Hodgkin_lymphoma": "a.Hodgkin lymphoma",
  "b.Non-Hodgkin_lymphoma": "b.Non-Hodgkin lymphoma",
  "c.Multiple_myeloma": "c.Multiple myeloma",
  "23.Leukaemia": "23.Leukaemia",
  "24.Other_malignant_neoplasms": "24.Other malignant neoplasms",
  "B.Other_neoplasms": "B.Other neoplasms",
  "C.Diabetes_mellitus": "C.Diabetes mellitus",
  "D.Endocrine,_blood,_immune_disorders": "D.Endocrine, blood, immune disorders",
  "1.Thalassaemias": "1.Thalassaemias",
  "2.Sickle_cell_disorders_and_trait": "2.Sickle cell disorders and trait",
  "3.Other_haemoglobinopathies_and_haemolytic_anaemias": "3.Other haemoglobinopathies and haemolytic anaemias",
  "4.Other_endocrine,_blood_and_immune_disorders": "4.Other endocrine, blood and immune disorders",
  "E.Mental_and_substance_use_disorders": "E.Mental and substance use disorders",
  "1.Depressive_disorders": "1.Depressive disorders",
  "2.Bipolar_disorder": "2.Bipolar disorder",
  "3.Schizophrenia": "3.Schizophrenia",
  "4.Alcohol_use_disorders": "4.Alcohol use disorders",
  "5.Drug_use_disorders": "5.Drug use disorders",
  "a.Opioid_use_disorders": "a.Opioid use disorders",
  "b.Cocaine_use_disorders": "b.Cocaine use disorders",
  "c.Amphetamine_use_disorders": "c.Amphetamine use disorders",
  "d.Cannabis_use_disorders": "d.Cannabis use disorders",
  "e.Other_drug_use_disorders": "e.Other drug use disorders",
  "6.Anxiety_disorders": "6.Anxiety disorders",
  "7.Eating_disorders": "7.Eating disorders",
  "8.Austism_and_Asperger_syndrome": "8.Austism and Asperger syndrome",
  "9.Childhood_behavioural_disorders": "9.Childhood behavioural disorders",
  "a.Attention_deficit_hyperactivity_syndrome": "a.Attention deficit/hyperactivity syndrome",
  "b.Conduct_disorder": "b.Conduct disorder",
  "10.Idiopathic_intellectual_disability": "10.Idiopathic intellectual disability",
  "11.Other_mental_and_behavioural_disorders": "11.Other mental and behavioural disorders",
  "F.Neurological_conditions": "F.Neurological conditions",
  "1.Alzheimer_disease_and_other_dementias": "1.Alzheimer disease and other dementias",
  "2.Parkinson_disease": "2.Parkinson disease",
  "3.Epilepsy": "3.Epilepsy",
  "4.Multiple_sclerosis": "4.Multiple sclerosis",
  "5.Migraine": "5.Migraine",
  "6.Non-migrane_headache": "6.Non-migrane headache",
  "7.Other_neurological_conditions": "7.Other neurological conditions",
  "G.Sense_organ_diseases": "G.Sense organ diseases",
  "1.Glaucoma": "1.Glaucoma",
  "2.Cataracts": "2.Cataracts",
  "3.Uncorrected_refractive_errors": "3.Uncorrected refractive errors",
  "4.Macular_degeneration": "4.Macular degeneration",
  "5.Other_vision_loss": "5.Other vision loss",
  "6.Other_hearing_loss": "6.Other hearing loss",
  "7.Other_sense_organ_disorders": "7.Other sense organ disorders",
  "H.Cardiovascular_diseases": "H.Cardiovascular diseases",
  "1.Rheumatic_heart_disease": "1.Rheumatic heart disease",
  "2.Hypertensive_heart_disease": "2.Hypertensive heart disease",
  "3.Ischaemic_heart_disease": "3.Ischaemic heart disease",
  "4.Stroke": "4.Stroke",
  "a.Ischaemic_stroke": "a.Ischaemic stroke",
  "b.Haemorrhagic_stroke": "b.Haemorrhagic stroke",
  "5.Cardiomyopathy,_myocarditis,_endocarditis": "5.Cardiomyopathy, myocarditis, endocarditis",
  "6.Other_circulatory_diseases": "6.Other circulatory diseases",
  "I.Respiratory_diseases": "I.Respiratory diseases",
  "1.Chronic_obstructive_pulmonary_disease": "1.Chronic obstructive pulmonary disease",
  "2.Asthma": "2.Asthma",
  "3.Other_respiratory_diseases": "3.Other respiratory diseases",
  "J.Digestive_diseases": "J.Digestive diseases",
  "1.Peptic_ulcer_disease": "1.Peptic ulcer disease",
  "2.Cirrhosis_of_the_liver": "2.Cirrhosis of the liver",
  "a.Cirrhosis_due_to_hepatitis_B": "a.Cirrhosis due to hepatitis B",
  "b.Cirrhosis_due_to_hepatitis_C": "b.Cirrhosis due to hepatitis C",
  "c.Cirrhosis_due_to_alcohol_use": "c.Cirrhosis due to alcohol use",
  "d.Other_liver_cirrhosis": "d.Other liver cirrhosis",
  "3.Appendicitis": "3.Appendicitis",
  "4.Gastritis_and_duodenitis": "4.Gastritis and duodenitis",
  "5.Paralytic_ileus_and_intestinal_obstruction": "5.Paralytic ileus and intestinal obstruction",
  "6.Inflammatory_bowel_disease": "6.Inflammatory bowel disease",
  "7.Gallbladder_and_biliary_diseases": "7.Gallbladder and biliary diseases",
  "8.Pancreatitis": "8.Pancreatitis",
  "9.Other_digestive_diseases": "9.Other digestive diseases",
  "K.Genitourinary_diseases": "K.Genitourinary diseases",
  "1.Kidney_diseases": "1.Kidney diseases",
  "a.Acute_glomerulonephritis": "a.Acute glomerulonephritis",
  "b.Chronic_kidney_disease_due_to_diabetes": "b.Chronic kidney disease due to diabetes",
  "c.Other_chronic_kidney_disease": "c.Other chronic kidney disease",
  "2.Benign_prostatic_hyperplasia": "2.Benign prostatic hyperplasia",
  "3.Urolithiasis": "3.Urolithiasis",
  "4.Other_urinary_diseases": "4.Other urinary diseases",
  "5.Infertility": "5.Infertility",
  "6.Gynecological_diseases": "6.Gynecological diseases",
  "L.Skin_diseases": "L.Skin diseases",
  "M.Musculoskeletal_diseases": "M.Musculoskeletal diseases",
  "1.Rheumatoid_arthritis": "1.Rheumatoid arthritis",
  "2.Osteoarthritis": "2.Osteoarthritis",
  "3.Gout": "3.Gout",
  "4.Back_and_neck_pain": "4.Back and neck pain",
  "5.Other_musculoskeletal_disorders": "5.Other musculoskeletal disorders",
  "N.Congenital_anomalies": "N.Congenital anomalies",
  "1.Neural_tube_defects": "1.Neural tube defects",
  "2.Cleft_lip_and_cleft_palate": "2.Cleft lip and cleft palate",
  "3.Down_syndrome": "3.Down syndrome",
  "4.Congenital_heart_anomalies": "4.Congenital heart anomalies",
  "5.Other_chromosomal_anomalies": "5.Other chromosomal anomalies",
  "6.Other_congenital_anomalies": "6.Other congenital anomalies",
  "O.Oral_conditions": "O.Oral conditions",
  "1.Dental_caries": "1.Dental caries",
  "2.Periodontal_disease": "2.Periodontal disease",
  "3.Edentulism": "3.Edentulism",
  "4.Other_oral_disorders": "4.Other oral disorders",
  "P.Sudden_infant_death_syndrome": "P.Sudden infant death syndrome",
  "III.Injuries": "III.Injuries",
  "A.Unintentional_injuries": "A.Unintentional injuries",
  "1.Road_injury": "1.Road injury",
  "2.Poisonings": "2.Poisonings",
  "3.Falls": "3.Falls",
  "4.Fire,_heat_and_hot_substances": "4.Fire, heat and hot substances",
  "5.Drowning": "5.Drowning",
  "6.Exposure_to_mechanical_forces": "6.Exposure to mechanical forces",
  "7.Natural_disasters": "7.Natural disasters",
  "8.Other_unintentional_injuries": "8.Other unintentional injuries",
  "B.Intentional_injuries": "B.Intentional injuries",
  "1.Self-harm": "1.Self-harm",
  "2.Interpersonal_violence": "2.Interpersonal violence",
  "3.Collective_violence_and_legal_intervention": "3.Collective violence and legal intervention",
  "C.Other_COVID-19_pandemic-related_outcomes": "C.Other\xa0COVID-19\xa0pandemic-related\xa0outcomes"
}